---
# DC2 fabric vars
fabric_name: dc2_fabric

underlay_routing_protocol: EBGP
overlay_routing_protocol: EBGP

p2p_uplinks_mtu: 9214

evpn_import_pruning: true

bgp_peer_groups:
  ipv4_underlay_peers:
    name: IPV4-UNDERLAY-PEERS
    password: EncryptedPasswordHere
  mlag_ipv4_underlay_peer:
    name: MLAG-IPV4-UNDERLAY-PEER
    password: EncryptedPasswordHere
  evpn_overlay_peers:
    name: EVPN-OVERLAY-LOCAL-PEERS
    password: EncryptedPasswordHere
  evpn_overlay_core:
    name: EVPN-OVERLAY-REMOTE-PEERS
    password: EncryptedPasswordHere

##################################################
# DC2 Spines                                     #
##################################################
spine:
  defaults:
    platform: ceos
    bgp_as: 65100
    loopback_ipv4_pool: 10.1.0.0/24
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'neighbor default send-community'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    - name: s1-Spine1
      id: 110
      mgmt_ip: 192.168.0.10/24
    - name: s1-Spine2
      id: 112
      mgmt_ip: 192.168.0.11/24

##################################################
# DC2 Leaf Pairs                                 #
##################################################
l3leaf:
  defaults:
    platform: ceos
    loopback_ipv4_pool: 10.231.0.0/24
    vtep_loopback_ipv4_pool: 10.231.1.0/24
    uplink_interfaces: [Ethernet97/1, Ethernet98/1]
    uplink_switches: [ISOC-ASPINE-1, ISOC-ASPINE-2]
    uplink_ipv4_pool: 10.231.4.0/22
    mlag_interfaces: [Ethernet103/1, Ethernet104/1]
    mlag_peer_ipv4_pool: 192.0.0.0/24
    mlag_peer_l3_ipv4_pool: 192.1.1.0/24
    mlag_port_channel_id: 1000
    virtual_router_mac_address: 00:1c:73:00:00:01
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'neighbor default send-community'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    spanning_tree_mode: rapid-pvst
    spanning_tree_priority: 0
    structured_config:
      spanning_tree:
        edge_port:
          bpduguard_default: true
  node_groups:
    ####################################################
    # ISOC CORP Border Leafs                           #
    ####################################################
    - group: BL_CORP
      platform: 7280R3
      structured_config:
        tcam_profile:
          system: vxlan-routing
        router_bgp:
          address_family_ipv4:
            networks:
              10.231.0.2/32:
              10.231.0.4/32:
              10.231.1.2/32:
      filter:
        tenants: [FE_DC]
        tags: ['CORP']
      bgp_as: 4200010199
      evpn_gateway:
        evpn_l2:
          enabled: true
        remote_peers:
        - hostname: SDC-ABL-1
          ip_address: 10.231.0.102
          bgp_as: 4200010299
        - hostname: SDC-ABL-2
          ip_address: 10.231.0.104
          bgp_as: 4200010299
      nodes:
        - name: ISOC-ABL-1
          id: 2
          mgmt_ip: 10.171.7.2/23
          uplink_switch_interfaces: [Ethernet3/36/1, Ethernet3/36/1]
          uplink_interfaces: [Ethernet29/1, Ethernet30/1]
          mlag_interfaces: [Ethernet31/1, Ethernet32/1]
          structured_config:
            router_bgp:
              neighbors:
                10.233.254.80:
                  remote_as: 65500
                  description: ISOC-CORE-1 VRF Default
                  peer_group: IPV4-UNDERLAY-PEERS
                10.233.254.82:
                  remote_as: 65500
                  description: ISOC-CORE-2 VRF Default
                  peer_group: IPV4-UNDERLAY-PEERS
        - name: ISOC-ABL-2
          id: 4
          mgmt_ip: 10.171.7.4/23
          uplink_switch_interfaces: [Ethernet4/36/1, Ethernet4/36/1]
          uplink_interfaces: [Ethernet29/1, Ethernet30/1]
          mlag_interfaces: [Ethernet31/1, Ethernet32/1]
          structured_config:
            router_bgp:
              neighbors:
                10.233.254.84:
                  remote_as: 65500
                  description: ISOC-CORE-1 VRF Default
                  peer_group: IPV4-UNDERLAY-PEERS
                10.233.254.86:
                  remote_as: 65500
                  description: ISOC-CORE-2 VRF Default
                  peer_group: IPV4-UNDERLAY-PEERS
    ####################################################
    # DC2 Leaf Pair 1                                  #
    ####################################################
    - group: LeafPair1
      filter:
        tenants: [FE_DC]
        tags: ['CORP']
      bgp_as: 65101
      nodes:
        - name: s2-Leaf1
          id: 114
          mgmt_ip: 192.168.0.12/24
          uplink_switch_interfaces: [Ethernet3/1/1, Ethernet3/1/1]
        - name: s2-Leaf2
          id: 116
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces: [Ethernet4/1/1, Ethernet4/1/1]